"""empty message

Revision ID: 219b044aff58
Revises: f2c7f96c73d9
Create Date: 2022-01-20 09:02:26.895109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219b044aff58'
down_revision = 'f2c7f96c73d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('ends_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ends_at', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'station', ['ends_at'], ['id'])
        batch_op.create_foreign_key(None, 'station', ['starts_at'], ['id'])

    # ### end Alembic commands ###
