"""empty message

Revision ID: 4aae81c95fc0
Revises: 1895194041f6
Create Date: 2022-01-05 04:06:55.880088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aae81c95fc0'
down_revision = '1895194041f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=17), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('railway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.Integer(), nullable=True),
    sa.Column('ends_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ends_at'], ['station.id'], ),
    sa.ForeignKeyConstraint(['starts_at'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Integer(), nullable=True),
    sa.Column('ends_at', sa.Integer(), nullable=True),
    sa.Column('length', sa.Numeric(), nullable=True),
    sa.Column('user_fee', sa.Numeric(), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('gauge', sa.Integer(), nullable=True),
    sa.Column('railway_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ends_at'], ['station.id'], ),
    sa.ForeignKeyConstraint(['railway_id'], ['railway.id'], ),
    sa.ForeignKeyConstraint(['starts_at'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stations')
    op.drop_table('warnings')
    op.drop_table('sections')
    op.drop_table('railways')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railways',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('starts_at', sa.INTEGER(), nullable=True),
    sa.Column('ends_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ends_at'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['starts_at'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('starts_at', sa.INTEGER(), nullable=True),
    sa.Column('ends_at', sa.INTEGER(), nullable=True),
    sa.Column('length', sa.NUMERIC(), nullable=True),
    sa.Column('user_fee', sa.NUMERIC(), nullable=True),
    sa.Column('max_speed', sa.INTEGER(), nullable=True),
    sa.Column('gauge', sa.INTEGER(), nullable=True),
    sa.Column('railway_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ends_at'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['railway_id'], ['railways.id'], ),
    sa.ForeignKeyConstraint(['starts_at'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state', sa.VARCHAR(length=17), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('warning')
    op.drop_table('section')
    op.drop_table('railway')
    op.drop_table('station')
    # ### end Alembic commands ###
