"""Initial db status

Revision ID: 5959f449803c
Revises: 
Create Date: 2022-01-04 10:32:43.780128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5959f449803c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(), nullable=True),
    sa.Column('user_fee', sa.Numeric(), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('gauge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    # ### end Alembic commands ###
