"""empty message

Revision ID: 720064206f91
Revises: 902bb6b0461f
Create Date: 2022-01-16 07:45:58.102522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720064206f91'
down_revision = '902bb6b0461f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warning', sa.Column('title', sa.String(length=30), nullable=True))
    op.add_column('warning', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_constraint(None, 'warning', type_='foreignkey')
    op.drop_column('warning', 'name')
    op.drop_column('warning', 'section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warning', sa.Column('section_id', sa.INTEGER(), nullable=False))
    op.add_column('warning', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.create_foreign_key(None, 'warning', 'section', ['section_id'], ['id'])
    op.drop_column('warning', 'description')
    op.drop_column('warning', 'title')
    # ### end Alembic commands ###
