"""empty message

Revision ID: 902bb6b0461f
Revises: 2c1380b79145
Create Date: 2022-01-16 07:42:58.529614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902bb6b0461f'
down_revision = '2c1380b79145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_warning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('warning_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['warning_id'], ['warning.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('warning', sa.Column('title', sa.String(length=30), nullable=False))
    op.add_column('warning', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_constraint(None, 'warning', type_='foreignkey')
    op.drop_column('warning', 'section_id')
    op.drop_column('warning', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warning', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.add_column('warning', sa.Column('section_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'warning', 'section', ['section_id'], ['id'])
    op.drop_column('warning', 'description')
    op.drop_column('warning', 'title')
    op.drop_table('section_warning')
    # ### end Alembic commands ###
