"""empty message

Revision ID: 9d42cd78c4a1
Revises: 2fa24ce3f6ac
Create Date: 2022-01-18 07:50:52.426581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d42cd78c4a1'
down_revision = '2fa24ce3f6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'railway', ['starts_at', 'ends_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'railway', type_='unique')
    # ### end Alembic commands ###
