"""empty message

Revision ID: b2cd9778054d
Revises: ff6ccd1a6f29
Create Date: 2022-01-18 13:39:25.587860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cd9778054d'
down_revision = 'ff6ccd1a6f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('UQ_starts_at_ends_at', type_='unique')
        batch_op.create_unique_constraint('uq_starts_at_ends_at', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('uq_starts_at_ends_at', type_='unique')
        batch_op.create_unique_constraint('UQ_starts_at_ends_at', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###
