"""empty message

Revision ID: cbc663cbb80f
Revises: ab0410e93872
Create Date: 2022-01-18 08:00:53.169727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc663cbb80f'
down_revision = 'ab0410e93872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.create_unique_constraint('disjoint_stations', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('disjoint_stations', type_='unique')

    # ### end Alembic commands ###
