"""empty message

Revision ID: e192c41001b5
Revises: b2cd9778054d
Create Date: 2022-01-18 13:49:41.508804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e192c41001b5'
down_revision = 'b2cd9778054d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('uq_starts_at_ends_at', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_starts_at_ends_at', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###
