"""Testing

Revision ID: ef9046ea9829
Revises: 4aae81c95fc0
Create Date: 2022-01-05 06:02:11.715244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9046ea9829'
down_revision = '4aae81c95fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('s', sa.String(length=17), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 's')
    # ### end Alembic commands ###
