"""empty message

Revision ID: f2c7f96c73d9
Revises: e192c41001b5
Create Date: 2022-01-18 13:57:27.955999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2c7f96c73d9'
down_revision = 'e192c41001b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.create_unique_constraint('test', ['starts_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('test', type_='unique')

    # ### end Alembic commands ###
