"""empty message

Revision ID: ff6ccd1a6f29
Revises: a06731ffd55b
Create Date: 2022-01-18 13:33:45.207329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6ccd1a6f29'
down_revision = 'a06731ffd55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('UQ_starts_at_ends_at', type_='unique')
        batch_op.create_unique_constraint('uq_starts_at_ends_at', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('railway', schema=None) as batch_op:
        batch_op.drop_constraint('uq_starts_at_ends_at', type_='unique')
        batch_op.create_unique_constraint('UQ_starts_at_ends_at', ['starts_at', 'ends_at'])

    # ### end Alembic commands ###
